name: vectorization
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - numpy
  - pandas >= 2.2.1
  - polars >= 0.20.16
  - duckdb-engine >= 0.11.2
  - python-duckdb >= 0.10.1
  - pydiverse-pipedag=0.7.2
  - pydiverse-transform
  - ibis-framework[duckdb]
  - lightgbm
  - xgboost
  - scikit-learn
  - matplotlib
  - connectorx >= 0.3.2
  - jupyter