[project]
name = "vectorization-tutorial"
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "win-64", "osx-arm64"]

[tasks]

[dependencies]
python = "3.11.*"
numpy = "==2.0.1"
pandas = ">=2.2.1"
polars = "==1.2.1"
duckdb-engine = "==0.12.1"
python-duckdb = "==0.10.3"
pydiverse-pipedag = "==0.7.2"
pydiverse-transform = "<0.2"
ibis-framework = "8.*"
lightgbm = "*"
xgboost = "*"
scikit-learn = "*"
matplotlib-base = "*"
# connectorx = ">=0.3.2"
jupyter = "*"
ipykernel = ">=6.29.5,<7"
sqlalchemy = "==2.0.32"
